# Generated by Django 5.0 on 2023-12-16 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0004_car_quantity"),
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="comment",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="posted_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="car.car"
            ),
        ),
    ]
